import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "@/provider/WalletProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { CardanoProvider } from "@/provider/CardenoProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={``}>
        <WalletProvider>
          {/* <CardanoProvider> */}
          <Navbar />
          {children}
          <Footer />
          {/* </CardanoProvider> */}
        </WalletProvider>
      </body>
    </html>
  );
}
